develop_config = {
    "environment": "develop",
    "mongo_connection_string": "mongodb://localhost/ertis_auth_test",
    "api_version": "v1",
    "application_secret": "AtqVaL11EHVPEpbu2mr0yZgKXj1BnRj0",
    "token_ttl": 60,
    "refresh_token_ttl": 600,
    "default_database": "ertis_auth_test",
    "verify_token": True,
    "error_handler": True,
    "debug": True,
    "host": "0.0.0.0",
    "port": 8888,
    "sentry_activate": False,
    "sentry_connection_string": 'https://1e79b0asdasdasdasd0c75784e9ea39ba35244470ee3:74c96d6ea1424dfcb397bd49b227442e@sentry.ertis.com/35?verify_ssl=0',
    "mail_activate": False,
    "mail_server": "smtp.googlemail.com",
    "mail_port": 465,
    "mail_username": "",
    "mail_password": "",
    "mail_use_tls": False,
    "mail_use_ssl": True,
    "major_version": 1,
    "minor_version": 4,
    "patch_version": 2,
    "version": "1.4.2"
}
